### ISSUE TITLE
Parametrize the SHA of Bower dependency

### ISSUE THREAD

**Issue by warpech** [Juicy/tattoo#1]
Parametrizing the SHA of Bower dependency as env variable in `.travis.yml`: https://docs.travis-ci.com/user/environment-variables/. 

Then the configuration can be overwritten in https://docs.travis-ci.com/user/triggering-builds#Customizing-the-build-configuration

**Comment by tomalec** [comment]
Fixed in https://github.com/Juicy/tattoo/pull/2
